targets:
  $default:
    sources:
      include: ["node/**", "lib/**"]
    builders:
      build_node_compilers|entrypoint:
        generate_for: ["node/**"]
        options:
          compiler: dart2js
